name: Backend CI
on:
  - pull_request
jobs:
  testing_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        folder: [cli, api, cmd, internal, provisioner]
    name: Running Go Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install --prefix dashboard
      - name: Run tests
        run: npm test --prefix dashboard
